apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-api
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: hrapp
        image: bobaddey/streamlit-be:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "400Mi"
            cpu: "100m"
          limits:
            memory: "600Mi"
            cpu: "150m"
      tolerations:
        - key: kubernetes.io/arch # IMPORTANT here
          operator: Equal
          value: "arm64"
          effect: NoSchedule
      imagePullSecrets: 
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: mlops
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000
    
