apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlitapp
        image: bobaddey/streamlit-fe:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "400Mi"
            cpu: "100m"
          limits:
            memory: "600Mi"
            cpu: "150m"
      tolerations:
        - key: kubernetes.io/arch # IMPORTANT here
          operator: Equal
          value: "arm64"
          effect: NoSchedule
      imagePullSecrets: 
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app
  namespace: mlops
spec:
  type: LoadBalancer
  selector:
    app: streamlit
  ports:
  - port: 8501
    targetPort: 8501
    
